# Generated by Django 3.2.23 on 2023-12-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20231209_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followers', to='profiles.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profiles_userprofile_friends_+', to='profiles.UserProfile'),
        ),
    ]
